# Application Configuration
SECRET_KEY: "not_a_secret"  # Secret key for session management
MONGO_URI: "mongodb://mongo:27017"  # MongoDB connection URI
MONGO_DBNAME: "miekkari_db"  # Name of the MongoDB database
MAIL:
  SERVER: "mailserver"  # SMTP server for sending emails
  PORT: 1025  # SMTP port, typically 587 for TLS
  USE_TLS: false  # Enable TLS for secure email sending
  USERNAME: "example@example.com"  # SMTP username
  PASSWORD: "example_password"  # SMTP password
  DEFAULT_SENDER: "example@example.com"  # Default sender email address

# Optional configurations
# SERVER_NAME: "www.example.com"  # Server name for the application
# PREFERRED_URL_SCHEME: "https"  # URL scheme (e.g., https)

PORT: 5002  # Application port
DEBUG: true  # Enable debugging mode for development
# SOS! Disable debug mode in production! 
# Debug mode exposes sensitive information and is not suitable for production environments!
# https://flask.palletsprojects.com/en/stable/config/#DEBUG

CDN_BASE_URL: "https://cdn.miekkari.localhost"

CACHE_TYPE: "SimpleCache"
ENABLE_CHAT: false

# S3 Configuration
S3:
  ACCESS_KEY: "example_access_key"  # Access key for S3
  SECRET_KEY: "example_secret_key"  # Secret key for S3
  ENDPOINT_URI: "http://localstack:4566"  # S3 endpoint URL

BABEL:
  DEFAULT_LOCALE: "fi"  # Default locale for the application
  SUPPORTED_LOCALES:
    - "fi"
    - "en"
    - "sv"
  