name: Security Scan

on:
  schedule:
    - cron: '0 * * * *'  # Runs at the start of every hour
  push:
    branches:
      - main
  pull_request:

jobs:
  security_scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bandit

    - name: Run Bandit Security Scan
      continue-on-error: true  # Ensure the job doesn't fail if bandit finds issues
      run: |
        bandit -r ./ -f json -o bandit-report.json

    - name: Upload Bandit Report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: bandit-report
        path: bandit-report.json
