name: Security Scan

on:
  schedule:
    - cron: '0 * * * *'  # Runs at the start of every hour
  push:
    branches:
      - main
  pull_request:

jobs:
  security_scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bandit

    - name: Run Bandit Security Scan
      id: bandit_scan
      continue-on-error: true  # Ensure the job doesn't fail if bandit finds issues
      run: |
        bandit -r ./ -f json -o bandit-report.json

    - name: Check for Bandit Issues
      id: check_bandit_issues
      run: |
        cat bandit-report.json
        issues=$(jq '.results | length' bandit-report.json)
        if [ $issues -gt 0 ]; then
          echo "Security issues found!"
          echo "::set-output name=issues_found::true"
        else
          echo "No security issues found."
          echo "::set-output name=issues_found::false"
        fi

    - name: Upload Bandit Report
      if: always()  # Always upload the report
      uses: actions/upload-artifact@v3
      with:
        name: bandit-report
        path: bandit-report.json
