name: Test and Format Pull Requests

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black

      - name: Run tests
        run: |
          pytest

      - name: Run black for code formatting
        run: |
          black .
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Apply black formatting" || echo "No changes to commit"
          git push origin HEAD:${{ github.event.pull_request.head.ref }}

      - name: Check for linting errors
        run: |
          flake8 .

      - name: Send message about problems
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Formatting issues were found and fixed."
          else
            echo "No formatting issues found."
          fi
